type SikakuListType = {
  [key: string]: string[];
};

export const SIKAKU_LIST: SikakuListType = {
  情報処理技術者試験: [
    "選択してください",
    "ITストラテジスト試験",
    "システム監査技術者試験",
    "プロジェクトマネージャ試験",
    "システムアーキテクト試験",
    "ITサービスマネージャ試験",
    "ネットワークスペシャリスト試験",
    "データベーススペシャリスト試験",
    "エンベデッドシステムスペシャリスト試験",
    "情報処理安全確保支援士試験",
    "応用情報技術者試験",
    "基本情報技術者試験",
    "情報セキュリティマネジメント試験",
  ],
  AWS: [
    "選択してください",
    "AWS Certified Advanced Networking - Specialty",
    "AWS Certified Machine Learning - Specialty",
    "AWS Certified Security - Specialty",
    "AWS Certified Solutions Architect - Professional",
    "AWS Certified DevOps Engineer - Professional",
    "AWS Certified Solutions Architect - Associate",
    "AWS Certified SysOps Administrator-Associate",
    "AWS Certified Developer - Associate",
    "AWS Certified Data Engineer - Associate",
    "AWS Certified Cloud Practitioner",
  ],
  Python: [
    "選択してください",
    "Python 3 エンジニア認定データ分析試験",
    "Python 3 エンジニア認定基礎試験",
  ],
  日本ディープランニング協会: ["選択してください", "G検定", "E資格"],
  OutSystems: [
    "選択してください",
    "Expert Traditional Web Developer  (OutSystems 11)",
    "Professional Traditional Web Developer  (OutSystems 11)",
  ],
  CompTIA: [
    "選択してください",
    "Advanced Security Practitioner",
    "Cloud Essentials",
    "Mobility+",
    "Cloud+",
    "Project+",
    "CDIA+",
    "CTT+",
    "Storage+",
    "Powered by SNIA Server+",
    "Security+",
    "Network+ A+",
  ],
  Linux: [
    "選択してください",
    "LPICレベル3・LinuCレベル3",
    "LPICレベル2・LinuCレベル2",
  ],
  HTML5プロフェッショナル: [
    "選択してください",
    "HTML5 Professional Certification Level.2",
    "HTML5 Professional Certification Level.1",
  ],
  日本語能力試験: [
    "選択してください",
    "N1",
    "N2",
    "N3",
  ],
};
